### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by Hardcore-fs** [Luzifer/rust-server#1]
sudo docker run --rm -ti -v /data/rust:/home/rustserver --name rust luzifer/rust-server auto-install

+ '[' -e /home/rustserver/rustserver ']'
+ cp /opt/rustserver /home/rustserver/rustserver
cp: cannot create regular file '/home/rustserver/rustserver': Permission denied

**Comment by Luzifer** [comment]
You need to ensure the `rustserver` user inside the container is able to write to the mounted volume. If the mounted directory does not exist, docker creates it writable only for the `root` user.

Doing a `chown 1000:1000 /data/rust` should be sufficient for this.
